### ISSUE TITLE
Rails requirement

### ISSUE THREAD

**Issue by HashNotAdam** [antulik/active_interaction-extras#12]
Having Rails as a dependency makes this gem very heavy to include in a gem that doesn't rely upon Rails. Is there a dependency in Rails you need that isn't included in active_interaction that we could isolate and include separately?

I'm developing a gem that is nothing more than an API client. While I will use it exclusively in Rails and, in all likelihood, I will be the only user of this gem, I'd hate to remove the possibility for someone else to use my gem outside of Rails

**Comment by antulik** [comment]
Good point. Fixed in v1.0.3
