### ISSUE TITLE
Extras::ModelFields#model_fields doesn't return values assigned from model attributes

### ISSUE THREAD

**Issue by kieranjogrady** [antulik/active_interaction-extras#14]
Since [v1.0.2 release](https://github.com/antulik/active_interaction-extras/compare/v1.0.1...v1.0.2#diff-638fd61777acdf408fb40d43ec0b6ae07156f7a4b6cfe179f7581f5445f87a44R71) the `Extras::ModelFields` mixin overrides `ActiveInteraction::Base#process_filters_and_inputs` to enable compatibility with `active_interaction` v4.0.2. This appears to have introduced an issue with the convenient `Extras::ModelFields#model_fields` getter since it depends on `ActiveInteraction::Base#inputs` returning values that are assigned to model fields filters by the overridden `process_filters_and_inputs` method i.e. the overridden method is assigning model fields values to filters but not the `inputs` data structure.

**Comment by kieranjogrady** [comment]
Hi @antulik, I hope you're keeping well. I'm working on a spec to surface this behaviour change and I'll shortly submit a PR for review at your convenience please 🙏.

**Comment by kieranjogrady** [comment]
#15 is submitted for review when you have a moment please.

**Comment by antulik** [comment]
@kieranjogrady thanks for reporting. It's fixed in master and will be released in the next version.

Related
https://github.com/antulik/active_interaction-extras/pull/15#issuecomment-1451431062
