### ISSUE TITLE
Extras::StrongParams#initialize assumes hash-like argument

### ISSUE THREAD

**Issue by kieranjogrady** [antulik/active_interaction-extras#16]
Since v1.0.2 the `Extras::StrongParams` mixin overrides `ActiveInteraction::Base#initialize` (instead of `ActiveInteraction::Base#process_inputs`) to implement `params` and `form_params` behaviour. An issue introduced with this change is that the overridden initializer is now called prior to `ActiveInteraction::Inputs#normalize_inputs!` which includes type checking guards for the received `inputs` argument. Without these guard, the overridden initializer raises `NoMethodError: undefined method 'key?'` exception when the `inputs` argument is not a hash-like data structure.

**Comment by kieranjogrady** [comment]
@antulik #17 is submitted for review at your convenience please 🙏

**Comment by antulik** [comment]
fixed in https://github.com/antulik/active_interaction-extras/pull/17
