### ISSUE TITLE
Nested Forms

### ISSUE THREAD

**Issue by spencersteiner** [antulik/active_interaction-extras#7]
Hey there! Decided to open up an issue here for discussion on Nested Forms after reaching out to @antulik. I'm curious about how others are writing nested forms using Active Interaction Extras (Or just plain Active Interaction if none of the extras functionality is required for that -- in which case we can move the discussion to Active Interaction if that feels more appropriate).

As an example scenario, given these two models: 
```ruby
class Car < ApplicationRecord
  has_many :parts
end

class Part < ApplicationRecord
  belongs_to :car
end
```

Is it recommended to have a single form object that takes inputs for creating both of these, and then composing a `CreateCar` and `CreatePart` interaction in the form object itself? Or would you instead have the `CreateCar` interaction be the form object, and have it compose the `CreatePart` interaction as part of its execution? (I've tried this using the `converter: :new` option, but validations no longer get mapped to the nested fields nicely which is one of my primary struggles in getting this working)

Thanks in advance! Let me know if my question can use any clarity, I'm happy to be more specific wherever I can.

**Comment by antulik** [comment]
> Is it recommended to have a single form object that takes inputs for creating both of these, and then composing a CreateCar and CreatePart interaction in the form object itself? 

That would be my preference. It might be more code to write but it will be more obvious what's going on. 

In the past I wrote my own sync logic of what `Part` models to add and remove. But you can use rails nested attributes for that as well.

If you are using array of hashes as input, form builder in the views won't work out of the box anymore. But it's not hard to get it work with few tweaks. I would build and validate records manually in the form object. If you want error messages for the nested object in the form, then you might need to use array of objects or `to_model` method (see below).

These days active interaction supports array of objects with `converter` option. I haven't tried it yet, but in theory that should make it easier. 

Another option is to create `to_model` method on the form object. It is handy when the form accepts a list of hashes, but you want to use default rails form builder. There are few other edge cases with that approach, but I used it successfully in the past. 

I think there could be a set of tools to simplify some of these solutions, but those nested forms have been rare in my experience so I always had one off solutions and never settled on a perfect solution.

I had plenty of composed form objects with 1-1 relationship, e.g. Car + CarOwner. For these I always use `model_fields` extension.

**Comment by spencersteiner** [comment]
@antulik Thanks for your response, this gives me some great ideas!
